### ISSUE TITLE
wx.TextEntryDialog can't run in thread now.

### ISSUE THREAD

**Issue by jekoie** [wxWidgets/wxPython#20]
wx.TextEntryDialog can't run in thread now.
```
Traceback (most recent call last):
  File "E:/AutoTest/main.py", line 946, in OnIdle
    data = self.serial.read(self.serial.inWaiting())
  File "C:\Python27\lib\site-packages\serial\serialutil.py", line 529, in inWaiting
    return self.in_waiting
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 253, in in_waiting
    if not win32.ClearCommError(self._port_handle, ctypes.byref(flags), ctypes.byref(comstat)):
ctypes.ArgumentError: argument 1: <class 'wx._core.wxAssertionError'>: C++ assertion "wxThread::IsMain()" failed at ..\..\src\msw\thread.cpp(1384) in wxMutexGuiLeaveOrEnter(): only main thread may call wxMutexGuiLeaveOrEnter()!
Unhandled exception in beginthreadex created thread:
Traceback (most recent call last):
  File "E:\AutoTest\module\product.py", line 492, in run
    bad_dlg.ShowModal()
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\msw\evtloop.cpp(182) in wxGUIEventLoop::Dispatch(): only the main thread can process Windows messages
```

**Comment by RobinD42** [comment]
This is not a bug. wxWidgets has never supported using GUI elements in non-main threads, and if it worked in the past before that assert was added in the code then it was just a happy accident.
